server:
  port: 8080
  servlet:
    context-path: /ordersrv

spring:
  application:
    name: ordersrvapi
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:h2:mem:test
    username: root
    password: root
    driverClassName: org.h2.Driver

jwt:
  secret: waqasahmed