# LOGGER LEVEL
logging:
  file:
    name: "/apps/logs/loginservice.log"
    max-history:  30
    max-size: 10MB
  pattern:
    console:  "%d{yyyy-MMM-dd HH:mm:ss.SSS} [%thread] %highlight(%-5level) %cyan(%logger{15}) - %msg %n"
    file: "%d{yyyy-MMM-dd HH:mm:ss} [%thread]  %highlight(%-5level) %boldyellow(%logger{15}) - %msg%"
  level:
    com:
      callsign:
        demo: DEBUG
  # H2
h2:
  console:
    enabled: true
jpa:
  show-sql: true
  hibernate:
    ddl-auto: create-drop
datasource:
  url: jdbc:h2:mem:logindb
  username: root
  password: root
  driverClassName: org.h2.Driver
#   JWT
jwt:
  secret: waqasahmed

environment:  "local"