server:
  port: 8081
  servlet:
    context-path: /loginsrv

spring:
  application:
    name: loginsrvapi
  h2:
    console:
      enabled: true
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: jdbc:h2:mem:logindb
    username: root
    password: root
    driverClassName: org.h2.Driver

jwt:
  secret: waqasahmed